In [ ]:
import pandas as pd
df = pd.read_csv('C:/Users/BEST LAPTOP/Desktop/AI/weather.csv')
df

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MIN temp (deg Celcius)  31 non-null     object
 1   Location                31 non-null     object
 2   Time                    31 non-null     object
 3   Wind                    31 non-null     object
 4   MAX temp (deg Celcius)  31 non-null     object
 5   Description             31 non-null     object
 6   Precipitation (in %)    31 non-null     object
 7   Date                    31 non-null     object
 8   Other Details           31 non-null     object
 9   Humidity (in %)         31 non-null     object
 10  Day                     31 non-null     object
dtypes: object(11)
memory usage: 2.8+ KB

In [4]:
df.describe()

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
count,31,31,31,31,31,31,31,31,31,31,31
unique,5,2,2,16,6,4,2,16,16,9,9
top,19,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,33,Sunny,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,29,Fri
freq,12,30,30,2,10,20,30,2,2,8,4

In [5]:
df.head()

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon

In [6]:
df.tail()

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [ ]:
df[df.duplicated()] #Shows only duplicate rows.

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [10]:
df[df['Location'].duplicated()] #Check duplicates in a specific column

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [11]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
dtype: bool

In [ ]:
df.drop_duplicates() # drop duplicates

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day

In [13]:
df.drop_duplicates(subset=['Location']) #remove duplictaed from specific col

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day

In [15]:
df.shape

(31, 11)

In [17]:
df.columns

Index(['MIN temp (deg Celcius)', 'Location', 'Time', 'Wind',
       'MAX temp (deg Celcius)', 'Description', 'Precipitation (in %)', 'Date',
       'Other Details', 'Humidity (in %)', 'Day'],
      dtype='object')

In [19]:
df.dtypes

MIN temp (deg Celcius)    object
Location                  object
Time                      object
Wind                      object
MAX temp (deg Celcius)    object
Description               object
Precipitation (in %)      object
Date                      object
Other Details             object
Humidity (in %)           object
Day                       object
dtype: object

In [ ]:
df.sort_values(by='Humidity (in %)') #sort on the assending

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day

In [21]:
df.sort_values(by='Humidity (in %)', ascending=False) #decending order

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon

In [22]:
df.isnull() #check nullvalues

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum() #Count null values

MIN temp (deg Celcius)    0
Location                  0
Time                      0
Wind                      0
MAX temp (deg Celcius)    0
Description               0
Precipitation (in %)      0
Date                      0
Other Details             0
Humidity (in %)           0
Day                       0
dtype: int64

In [24]:
df.dropna() #drop null values

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [25]:
df.fillna(0) #fill null values with zero

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [27]:
df['Wind'] # select single col

0      NE 2 km/h
1     NNW 7 km/h
2     SSW 5 km/h
3     WSW 9 km/h
4       N 9 km/h
5       W 8 km/h
6     SSE 7 km/h
7     SSW 9 km/h
8       E 7 km/h
9     NE 10 km/h
10     NE 7 km/h
11    ENE 6 km/h
12      E 6 km/h
13    ESE 5 km/h
14    NNW 5 km/h
15           Wind
16     NE 2 km/h
17    NNW 7 km/h
18    SSW 5 km/h
19    WSW 9 km/h
20      N 9 km/h
21      W 8 km/h
22    SSE 7 km/h
23    SSW 9 km/h
24      E 7 km/h
25    NE 10 km/h
26     NE 7 km/h
27    ENE 6 km/h
28      E 6 km/h
29    ESE 5 km/h
30    NNW 5 km/h
Name: Wind, dtype: object

In [29]:
df[['Location','Wind']] #select multiple col

                         Location         Wind
0   Bharsul, India 10-day Weather   NE 2 km/h
1   Bharsul, India 10-day Weather  NNW 7 km/h
2   Bharsul, India 10-day Weather  SSW 5 km/h
3   Bharsul, India 10-day Weather  WSW 9 km/h
4   Bharsul, India 10-day Weather    N 9 km/h
5   Bharsul, India 10-day Weather    W 8 km/h
6   Bharsul, India 10-day Weather  SSE 7 km/h
7   Bharsul, India 10-day Weather  SSW 9 km/h
8   Bharsul, India 10-day Weather    E 7 km/h
9   Bharsul, India 10-day Weather  NE 10 km/h
10  Bharsul, India 10-day Weather   NE 7 km/h
11  Bharsul, India 10-day Weather  ENE 6 km/h
12  Bharsul, India 10-day Weather    E 6 km/h
13  Bharsul, India 10-day Weather  ESE 5 km/h
14  Bharsul, India 10-day Weather  NNW 5 km/h
15                       Location         Wind
16  Bharsul, India 10-day Weather   NE 2 km/h
17  Bharsul, India 10-day Weather  NNW 7 km/h
18  Bharsul, India 10-day Weather  SSW 5 km/h
19  Bharsul, India 10-day Weather  WSW 9 km/h
20  Bharsul, India 10-day Weather    N 9 km/h
21  Bharsul, India 10-day Weather    W 8 km/h
22  Bharsul, India 10-day Weather  SSE 7 km/h
23  Bharsul, India 10-day Weather  SSW 9 km/h
24  Bharsul, India 10-day Weather    E 7 km/h
25  Bharsul, India 10-day Weather  NE 10 km/h
26  Bharsul, India 10-day Weather   NE 7 km/h
27  Bharsul, India 10-day Weather  ENE 6 km/h
28  Bharsul, India 10-day Weather    E 6 km/h
29  Bharsul, India 10-day Weather  ESE 5 km/h
30  Bharsul, India 10-day Weather  NNW 5 km/h

In [36]:
df[df['Humidity (in %)'] > 10]

TypeError: '>' not supported between instances of 'str' and 'int'

In [40]:
df.rename(columns={'Humidity (in %)':'Humidity'}, inplace=True) #rename the col

In [41]:
df

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity,Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [46]:
df[df['MAX temp (deg Celcius)'] > 30]

TypeError: '>' not supported between instances of 'str' and 'int'

In [48]:
df[df['Location'] == 'Bharsul, India']

Empty DataFrame
Columns: [MIN temp (deg Celcius), Location, Time, Wind, MAX temp (deg Celcius), Description, Precipitation (in %), Date, Other Details, Humidity, Day]
Index: []

In [49]:
df.groupby('Location')['MAX temp (deg Celcius)'].mean()

TypeError: agg function failed [how->mean,dtype->object]